stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build twentyone:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - twentyone
  script:
    - ./gradlew assemble
