stages:
  - build
  - deploy

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

build twentyone:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - twentyone
  script:
    - ./gradlew assemble

deploy twentyone:
  stage: deploy
  tags:
    - twentyone
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
    - sudo -S service twentyone restart
