server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
#    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jpa_metadata_defaults: false
    #   hibernate:
    #   ddl-auto: none
    # database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:postgresql://localhost:5632/postgres
    username: root
    password: root
#      url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE
#      driverClassName: org.h2.Driver
#      username: test
#      password: test
  h2:
    console:
      enabled: true