server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        temp:
          use_jpa_metadata_defaults: false
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true